# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'C2(dictionary)cyZEiS.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QGridLayout, QLabel,
    QPushButton, QSizePolicy, QStackedWidget, QToolBox,
    QWidget)
import C2_Demo_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1440, 860)
        self.gridLayoutWidget = QWidget(Form)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 1441, 861))
        
        self.gridLayout_C = QGridLayout(self.page_main_C)
        self.gridLayout_C.setObjectName(u"gridLayout_C")
        self.gridLayout_C.setContentsMargins(0, 0, 0, 0)
        self.widget_C = QWidget(self.gridLayoutWidget)
        self.widget_C.setObjectName(u"widget_C")
        self.lb_backgroundLineI_C = QLabel(self.widget_C)
        self.lb_backgroundLineI_C.setObjectName(u"lb_backgroundLineI_C")
        self.lb_backgroundLineI_C.setGeometry(QRect(0, 0, 281, 860))
        self.lb_backgroundLineI_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.tb_box_C = QToolBox(self.widget_C)
        self.tb_box_C.setObjectName(u"tb_box_C")
        self.tb_box_C.setGeometry(QRect(0, 0, 271, 861))
        self.tb_box_C.setStyleSheet(u"")
        self.page_BoxI_C = QWidget()
        self.page_BoxI_C.setObjectName(u"page_BoxI_C")
        self.page_BoxI_C.setGeometry(QRect(0, 0, 271, 28))
        self.page_BoxI_C.setMinimumSize(QSize(271, 0))
        self.pb_uiArgument_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_uiArgument_BoxI_C.setObjectName(u"pb_uiArgument_BoxI_C")
        self.pb_uiArgument_BoxI_C.setGeometry(QRect(20, 120, 231, 61))
        self.pb_uiArgument_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_downTutorial_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_downTutorial_BoxI_C.setObjectName(u"pb_downTutorial_BoxI_C")
        self.pb_downTutorial_BoxI_C.setGeometry(QRect(20, 210, 231, 61))
        self.pb_downTutorial_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_uiMadeRule_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_uiMadeRule_BoxI_C.setObjectName(u"pb_uiMadeRule_BoxI_C")
        self.pb_uiMadeRule_BoxI_C.setGeometry(QRect(20, 300, 231, 61))
        self.pb_uiMadeRule_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_mind_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_mind_BoxI_C.setObjectName(u"pb_mind_BoxI_C")
        self.pb_mind_BoxI_C.setGeometry(QRect(20, 390, 231, 61))
        self.pb_mind_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_uiDictionary_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_uiDictionary_BoxI_C.setObjectName(u"pb_uiDictionary_BoxI_C")
        self.pb_uiDictionary_BoxI_C.setGeometry(QRect(20, 480, 231, 61))
        self.pb_uiDictionary_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_flowTutorial_BoxI_C = QPushButton(self.page_BoxI_C)
        self.pb_flowTutorial_BoxI_C.setObjectName(u"pb_flowTutorial_BoxI_C")
        self.pb_flowTutorial_BoxI_C.setGeometry(QRect(20, 30, 231, 61))
        self.pb_flowTutorial_BoxI_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_background_BoxI_C = QLabel(self.page_BoxI_C)
        self.lb_background_BoxI_C.setObjectName(u"lb_background_BoxI_C")
        self.lb_background_BoxI_C.setGeometry(QRect(-8, -5, 281, 781))
        self.lb_background_BoxI_C.setPixmap(QPixmap(u":/old/C2(dictionary)/lb_box_background_C.jpg"))
        self.tb_box_C.addItem(self.page_BoxI_C, u"\u8f6f\u4ef6\u4f7f\u7528\u6559\u7a0b")
        self.lb_background_BoxI_C.raise_()
        self.pb_uiArgument_BoxI_C.raise_()
        self.pb_downTutorial_BoxI_C.raise_()
        self.pb_uiMadeRule_BoxI_C.raise_()
        self.pb_mind_BoxI_C.raise_()
        self.pb_uiDictionary_BoxI_C.raise_()
        self.pb_flowTutorial_BoxI_C.raise_()
        self.page_BoxII_C = QWidget()
        self.page_BoxII_C.setObjectName(u"page_BoxII_C")
        self.page_BoxII_C.setGeometry(QRect(0, 0, 98, 28))
        self.pb_madeRule_BoxII_C = QPushButton(self.page_BoxII_C)
        self.pb_madeRule_BoxII_C.setObjectName(u"pb_madeRule_BoxII_C")
        self.pb_madeRule_BoxII_C.setGeometry(QRect(20, 30, 231, 61))
        self.pb_madeRule_BoxII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_userRule_BoxII_C = QPushButton(self.page_BoxII_C)
        self.pb_userRule_BoxII_C.setObjectName(u"pb_userRule_BoxII_C")
        self.pb_userRule_BoxII_C.setGeometry(QRect(20, 120, 231, 61))
        self.pb_userRule_BoxII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_licence_BoxII_C = QPushButton(self.page_BoxII_C)
        self.pb_licence_BoxII_C.setObjectName(u"pb_licence_BoxII_C")
        self.pb_licence_BoxII_C.setGeometry(QRect(20, 210, 231, 61))
        self.pb_licence_BoxII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_disclaimer_BoxII_C = QPushButton(self.page_BoxII_C)
        self.pb_disclaimer_BoxII_C.setObjectName(u"pb_disclaimer_BoxII_C")
        self.pb_disclaimer_BoxII_C.setGeometry(QRect(20, 310, 231, 61))
        self.pb_disclaimer_BoxII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_background_BoxII_C = QLabel(self.page_BoxII_C)
        self.lb_background_BoxII_C.setObjectName(u"lb_background_BoxII_C")
        self.lb_background_BoxII_C.setGeometry(QRect(0, 0, 271, 771))
        self.lb_background_BoxII_C.setPixmap(QPixmap(u":/old/C2(dictionary)/lb_box_background_C.jpg"))
        self.tb_box_C.addItem(self.page_BoxII_C, u"\u5236\u4f5c\u534f\u8bae")
        self.lb_background_BoxII_C.raise_()
        self.pb_madeRule_BoxII_C.raise_()
        self.pb_userRule_BoxII_C.raise_()
        self.pb_licence_BoxII_C.raise_()
        self.pb_disclaimer_BoxII_C.raise_()
        self.page_BoxIII_C = QWidget()
        self.page_BoxIII_C.setObjectName(u"page_BoxIII_C")
        self.page_BoxIII_C.setGeometry(QRect(0, 0, 271, 771))
        self.pb_introduce_BoxIII_C = QPushButton(self.page_BoxIII_C)
        self.pb_introduce_BoxIII_C.setObjectName(u"pb_introduce_BoxIII_C")
        self.pb_introduce_BoxIII_C.setGeometry(QRect(20, 30, 231, 61))
        self.pb_introduce_BoxIII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_contact_BoxIII_C = QPushButton(self.page_BoxIII_C)
        self.pb_contact_BoxIII_C.setObjectName(u"pb_contact_BoxIII_C")
        self.pb_contact_BoxIII_C.setGeometry(QRect(20, 120, 231, 61))
        self.pb_contact_BoxIII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pb_joinUs_BoxIII_C = QPushButton(self.page_BoxIII_C)
        self.pb_joinUs_BoxIII_C.setObjectName(u"pb_joinUs_BoxIII_C")
        self.pb_joinUs_BoxIII_C.setGeometry(QRect(20, 210, 231, 61))
        self.pb_joinUs_BoxIII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lb_background_BoxIII_C = QLabel(self.page_BoxIII_C)
        self.lb_background_BoxIII_C.setObjectName(u"lb_background_BoxIII_C")
        self.lb_background_BoxIII_C.setGeometry(QRect(0, 0, 271, 771))
        self.lb_background_BoxIII_C.setPixmap(QPixmap(u":/old/C2(dictionary)/lb_box_background_C.jpg"))
        self.pb_subsidize_BoxIII_C = QPushButton(self.page_BoxIII_C)
        self.pb_subsidize_BoxIII_C.setObjectName(u"pb_subsidize_BoxIII_C")
        self.pb_subsidize_BoxIII_C.setGeometry(QRect(20, 300, 231, 61))
        self.pb_subsidize_BoxIII_C.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.tb_box_C.addItem(self.page_BoxIII_C, u"\u5173\u4e8eTG studio")
        self.lb_background_BoxIII_C.raise_()
        self.pb_introduce_BoxIII_C.raise_()
        self.pb_contact_BoxIII_C.raise_()
        self.pb_joinUs_BoxIII_C.raise_()
        self.pb_subsidize_BoxIII_C.raise_()
        self.lb_backgroundLineII_C = QLabel(self.widget_C)
        self.lb_backgroundLineII_C.setObjectName(u"lb_backgroundLineII_C")
        self.lb_backgroundLineII_C.setGeometry(QRect(0, 0, 200, 840))
        self.lb_backgroundLineII_C.setStyleSheet(u"background-color: rgb(85, 0, 127);")
        self.sw_content_C = QStackedWidget(self.widget_C)
        self.sw_content_C.setObjectName(u"sw_content_C")
        self.sw_content_C.setGeometry(QRect(270, 0, 1171, 861))
        self.page_content4_BoxI_C = QWidget()
        self.page_content4_BoxI_C.setObjectName(u"page_content4_BoxI_C")
        self.lb_content_background4I_C = QLabel(self.page_content4_BoxI_C)
        self.lb_content_background4I_C.setObjectName(u"lb_content_background4I_C")
        self.lb_content_background4I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background4I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content4_BoxI_C)
        self.page_content1_BoxI_C = QWidget()
        self.page_content1_BoxI_C.setObjectName(u"page_content1_BoxI_C")
        self.lb_content_background1I_C = QLabel(self.page_content1_BoxI_C)
        self.lb_content_background1I_C.setObjectName(u"lb_content_background1I_C")
        self.lb_content_background1I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background1I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.lb_BV_Box1III_C = QLabel(self.page_content1_BoxI_C)
        self.lb_BV_Box1III_C.setObjectName(u"lb_BV_Box1III_C")
        self.lb_BV_Box1III_C.setGeometry(QRect(0, 0, 451, 51))
        self.lb_BV_Box1III_C.setStyleSheet(u"background-color:rgb(20, 20, 24);\n"
"font: 75 20pt \"\u5fae\u8f6f\u96c5\u9ed1\";\n"
"color:rgb(255, 255, 255);")
        self.graView_viede_Box1III_C = QGraphicsView(self.page_content1_BoxI_C)
        self.graView_viede_Box1III_C.setObjectName(u"graView_viede_Box1III_C")
        self.graView_viede_Box1III_C.setGeometry(QRect(60, 80, 1050, 650))
        self.sw_content_C.addWidget(self.page_content1_BoxI_C)
        self.page_content2_BoxI_C = QWidget()
        self.page_content2_BoxI_C.setObjectName(u"page_content2_BoxI_C")
        self.lb_content_background2I_C = QLabel(self.page_content2_BoxI_C)
        self.lb_content_background2I_C.setObjectName(u"lb_content_background2I_C")
        self.lb_content_background2I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background2I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.graView_viede_Box2I_C = QGraphicsView(self.page_content2_BoxI_C)
        self.graView_viede_Box2I_C.setObjectName(u"graView_viede_Box2I_C")
        self.graView_viede_Box2I_C.setGeometry(QRect(60, 80, 1050, 650))
        self.lb_BV_Box2I_C = QLabel(self.page_content2_BoxI_C)
        self.lb_BV_Box2I_C.setObjectName(u"lb_BV_Box2I_C")
        self.lb_BV_Box2I_C.setGeometry(QRect(0, 0, 451, 51))
        self.lb_BV_Box2I_C.setStyleSheet(u"background-color:rgb(20, 20, 24);\n"
"font: 75 20pt \"\u5fae\u8f6f\u96c5\u9ed1\";\n"
"color:rgb(255, 255, 255);")
        self.sw_content_C.addWidget(self.page_content2_BoxI_C)
        self.page_content3_BoxI_C = QWidget()
        self.page_content3_BoxI_C.setObjectName(u"page_content3_BoxI_C")
        self.lb_content_background3I_C = QLabel(self.page_content3_BoxI_C)
        self.lb_content_background3I_C.setObjectName(u"lb_content_background3I_C")
        self.lb_content_background3I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background3I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.graView_viede_Box3I_C = QGraphicsView(self.page_content3_BoxI_C)
        self.graView_viede_Box3I_C.setObjectName(u"graView_viede_Box3I_C")
        self.graView_viede_Box3I_C.setGeometry(QRect(60, 80, 1050, 650))
        self.lb_BV_Box3I_C = QLabel(self.page_content3_BoxI_C)
        self.lb_BV_Box3I_C.setObjectName(u"lb_BV_Box3I_C")
        self.lb_BV_Box3I_C.setGeometry(QRect(0, 0, 451, 51))
        self.lb_BV_Box3I_C.setStyleSheet(u"background-color:rgb(20, 20, 24);\n"
"font: 75 20pt \"\u5fae\u8f6f\u96c5\u9ed1\";\n"
"color:rgb(255, 255, 255);")
        self.sw_content_C.addWidget(self.page_content3_BoxI_C)
        self.page_content6_BoxI_C = QWidget()
        self.page_content6_BoxI_C.setObjectName(u"page_content6_BoxI_C")
        self.lb_content_background6I_C = QLabel(self.page_content6_BoxI_C)
        self.lb_content_background6I_C.setObjectName(u"lb_content_background6I_C")
        self.lb_content_background6I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background6I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content6_BoxI_C)
        self.page_content4_BoxIII_C = QWidget()
        self.page_content4_BoxIII_C.setObjectName(u"page_content4_BoxIII_C")
        self.lb_content_background4III_C = QLabel(self.page_content4_BoxIII_C)
        self.lb_content_background4III_C.setObjectName(u"lb_content_background4III_C")
        self.lb_content_background4III_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background4III_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content4_BoxIII_C)
        self.page_content1_BoxII_C = QWidget()
        self.page_content1_BoxII_C.setObjectName(u"page_content1_BoxII_C")
        self.lb_content_background1II_C = QLabel(self.page_content1_BoxII_C)
        self.lb_content_background1II_C.setObjectName(u"lb_content_background1II_C")
        self.lb_content_background1II_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background1II_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content1_BoxII_C)
        self.page_content2_BoxII_C = QWidget()
        self.page_content2_BoxII_C.setObjectName(u"page_content2_BoxII_C")
        self.lb_content_background2II_C = QLabel(self.page_content2_BoxII_C)
        self.lb_content_background2II_C.setObjectName(u"lb_content_background2II_C")
        self.lb_content_background2II_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background2II_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content2_BoxII_C)
        self.page_content3_BoxII_C = QWidget()
        self.page_content3_BoxII_C.setObjectName(u"page_content3_BoxII_C")
        self.lb_content_background3II_C = QLabel(self.page_content3_BoxII_C)
        self.lb_content_background3II_C.setObjectName(u"lb_content_background3II_C")
        self.lb_content_background3II_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background3II_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content3_BoxII_C)
        self.page_content4_BoxII_C = QWidget()
        self.page_content4_BoxII_C.setObjectName(u"page_content4_BoxII_C")
        self.lb_content_background4II_C = QLabel(self.page_content4_BoxII_C)
        self.lb_content_background4II_C.setObjectName(u"lb_content_background4II_C")
        self.lb_content_background4II_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background4II_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content4_BoxII_C)
        self.page_content1_BoxIII_C = QWidget()
        self.page_content1_BoxIII_C.setObjectName(u"page_content1_BoxIII_C")
        self.lb_background1III_C = QLabel(self.page_content1_BoxIII_C)
        self.lb_background1III_C.setObjectName(u"lb_background1III_C")
        self.lb_background1III_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_background1III_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content1_BoxIII_C)
        self.page_content2_BoxIII_C = QWidget()
        self.page_content2_BoxIII_C.setObjectName(u"page_content2_BoxIII_C")
        self.lb_content_background2III_C = QLabel(self.page_content2_BoxIII_C)
        self.lb_content_background2III_C.setObjectName(u"lb_content_background2III_C")
        self.lb_content_background2III_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background2III_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content2_BoxIII_C)
        self.page_content3_BoxIII_C = QWidget()
        self.page_content3_BoxIII_C.setObjectName(u"page_content3_BoxIII_C")
        self.lb_content_background3III_C = QLabel(self.page_content3_BoxIII_C)
        self.lb_content_background3III_C.setObjectName(u"lb_content_background3III_C")
        self.lb_content_background3III_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background3III_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content3_BoxIII_C)
        self.page_content5_BoxI_C = QWidget()
        self.page_content5_BoxI_C.setObjectName(u"page_content5_BoxI_C")
        self.lb_content_background5I_C = QLabel(self.page_content5_BoxI_C)
        self.lb_content_background5I_C.setObjectName(u"lb_content_background5I_C")
        self.lb_content_background5I_C.setGeometry(QRect(0, 0, 1170, 860))
        self.lb_content_background5I_C.setStyleSheet(u"background-color: rgb(45, 43, 53);")
        self.sw_content_C.addWidget(self.page_content5_BoxI_C)
        self.pb_exit_C = QPushButton(self.widget_C)
        self.pb_exit_C.setObjectName(u"pb_exit_C")
        self.pb_exit_C.setGeometry(QRect(1294, 803, 111, 41))
        self.pb_exit_C.setStyleSheet(u"background-color: rgb(0, 153, 255);\n"
"font: 16pt \"\u5fae\u8f6f\u96c5\u9ed1\";")
        self.lb_backgroundLineI_C.raise_()
        self.lb_backgroundLineII_C.raise_()
        self.tb_box_C.raise_()
        self.sw_content_C.raise_()
        self.pb_exit_C.raise_()

        self.gridLayout_C.addWidget(self.widget_C, 0, 0, 1, 1)


        self.retranslateUi(Form)

        self.tb_box_C.setCurrentIndex(2)
        self.sw_content_C.setCurrentIndex(12)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.lb_backgroundLineI_C.setText("")
        self.pb_uiArgument_BoxI_C.setText(QCoreApplication.translate("Form", u"\u5e03\u5c40\u53c2\u6570\u4f7f\u7528\u6559\u7a0b", None))
        self.pb_downTutorial_BoxI_C.setText(QCoreApplication.translate("Form", u"\u5bfc\u51fa\u6559\u7a0b", None))
        self.pb_uiMadeRule_BoxI_C.setText(QCoreApplication.translate("Form", u"\u4e8c\u521bUI\u81ea\u5b9a\u4e49\u6a21\u677f\u89c4\u8303", None))
        self.pb_mind_BoxI_C.setText(QCoreApplication.translate("Form", u"\u6ce8\u610f\u4e8b\u9879", None))
        self.pb_uiDictionary_BoxI_C.setText(QCoreApplication.translate("Form", u"\u5e03\u5c40\u53c2\u6570\u53c2\u8003\u6587\u6863", None))
        self.pb_flowTutorial_BoxI_C.setText(QCoreApplication.translate("Form", u"\u6d41\u7a0b\u56fe\u4f7f\u7528\u6559\u7a0b", None))
        self.lb_background_BoxI_C.setText("")
        self.tb_box_C.setItemText(self.tb_box_C.indexOf(self.page_BoxI_C), QCoreApplication.translate("Form", u"\u8f6f\u4ef6\u4f7f\u7528\u6559\u7a0b", None))
        self.pb_madeRule_BoxII_C.setText(QCoreApplication.translate("Form", u"\u5f15\u64ce\u4e8c\u521b\u534f\u8bae", None))
        self.pb_userRule_BoxII_C.setText(QCoreApplication.translate("Form", u"\u7528\u6237\u6761\u6b3e", None))
        self.pb_licence_BoxII_C.setText(QCoreApplication.translate("Form", u"\u5546\u7528\u8bb8\u53ef\u8bc1", None))
        self.pb_disclaimer_BoxII_C.setText(QCoreApplication.translate("Form", u"\u514d\u8d23\u58f0\u660e", None))
        self.lb_background_BoxII_C.setText("")
        self.tb_box_C.setItemText(self.tb_box_C.indexOf(self.page_BoxII_C), QCoreApplication.translate("Form", u"\u5236\u4f5c\u534f\u8bae", None))
        self.pb_introduce_BoxIII_C.setText(QCoreApplication.translate("Form", u"\u7b80\u4ecb", None))
        self.pb_contact_BoxIII_C.setText(QCoreApplication.translate("Form", u"\u8054\u7cfb\u65b9\u5f0f", None))
        self.pb_joinUs_BoxIII_C.setText(QCoreApplication.translate("Form", u"\u52a0\u5165\u6211\u4eec", None))
        self.lb_background_BoxIII_C.setText("")
        self.pb_subsidize_BoxIII_C.setText(QCoreApplication.translate("Form", u"\u8d44\u52a9\u6211\u4eec", None))
        self.tb_box_C.setItemText(self.tb_box_C.indexOf(self.page_BoxIII_C), QCoreApplication.translate("Form", u"\u5173\u4e8eTG studio", None))
        self.lb_backgroundLineII_C.setText("")
        self.lb_content_background4I_C.setText("")
        self.lb_content_background1I_C.setText("")
        self.lb_BV_Box1III_C.setText(QCoreApplication.translate("Form", u"\u89c6\u9891\uff1aBV114514", None))
        self.lb_content_background2I_C.setText("")
        self.lb_BV_Box2I_C.setText(QCoreApplication.translate("Form", u"\u89c6\u9891\uff1aBV114514", None))
        self.lb_content_background3I_C.setText("")
        self.lb_BV_Box3I_C.setText(QCoreApplication.translate("Form", u"\u89c6\u9891\uff1aBV114514", None))
        self.lb_content_background6I_C.setText("")
        self.lb_content_background4III_C.setText("")
        self.lb_content_background1II_C.setText("")
        self.lb_content_background2II_C.setText("")
        self.lb_content_background3II_C.setText("")
        self.lb_content_background4II_C.setText("")
        self.lb_background1III_C.setText("")
        self.lb_content_background2III_C.setText("")
        self.lb_content_background3III_C.setText("")
        self.lb_content_background5I_C.setText("")
        self.pb_exit_C.setText(QCoreApplication.translate("Form", u"EXIT", None))
    # retranslateUi

